# Generated by Django 5.2.18 on 2026-10-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('enlace', models.URLField(verbose_name='enlace al proyecto')),
                ('estado', models.CharField(choices=[('terminado', 'Terminado'), ('en_desarrollo', 'En desarrollo')], default='terminado', max_length=20)),
                ('colaboradores', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text='Mostrar en el inicio y el menú de proyectos.')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='proyectos/')),
                ('archivo_estatico', models.CharField(blank=True, help_text='Para imágenes existentes en portfolio/imagenes/. Si subís una imagen, dejá este campo vacío.', max_length=200, verbose_name='archivo estático')),
                ('alt', models.CharField(max_length=200, verbose_name='descripción de la imagen')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='portfolio.proyecto')),
            ],
            options={
                'verbose_name': 'imagen del proyecto',
                'verbose_name_plural': 'imágenes del proyecto',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
